[package]
name = "golden_apple"
version = "1.17.0-alpha-1"
authors = ["thisjaiden"]
edition = "2018"
description = "A Rust library for decoding and sharing Minecraft data types"
repository = "https://github.com/thisjaiden/golden_apple"
readme = "README.md"
license = "MIT"

[dependencies]
